name: OSV-Scanner Scheduled Scan

on:
  schedule:
    - cron: "30 12 * * 1"
  push:
    branches: [ qortium-6.1.5 ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache local Maven repository
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-osv-${{ hashFiles('**/pom.xml', 'lib/**/*.pom', 'lib/**/*.jar') }}
          restore-keys: |
            ${{ runner.os }}-maven-osv-
            ${{ runner.os }}-maven-

      - name: Set up the Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Maven dependency SBOM
        run: |
          mvn -B -U org.cyclonedx:cyclonedx-maven-plugin:2.9.1:makeBom \
            -DskipTests \
            -DoutputFormat=json \
            -DoutputName=bom.cdx \
            --file pom.xml

      - name: Run scanner
        uses: google/osv-scanner-action/osv-scanner-action@v2.5.0
        with:
          scan-args: |-
            --output=results.json
            --format=json
            -L target/bom.cdx.json
        continue-on-error: true

      - name: Run osv-scanner-reporter
        uses: google/osv-scanner-action/osv-reporter-action@v2.5.0
        with:
          scan-args: |-
            --output=results.sarif
            --new=results.json
            --gh-annotations=false
            --fail-on-vuln=true

      - name: Upload artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: OSV Scanner SARIF file
          path: results.sarif
          retention-days: 5

      - name: Upload to code-scanning
        if: ${{ !cancelled() }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif

      - name: Print Code Scanning URL
        if: ${{ !cancelled() }}
        run: |
          echo "View the OSV-Scanner results in the Security tab:"
          echo "${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=is%3Aopen+branch%3A${GITHUB_REF_NAME}+tool%3Aosv-scanner"
